import type { FactsStore } from "./types";
import generated from "./internal/registry-facts.generated.json";

/**
 * Registry facts for every locked package, generated by `npm run oss:credits`
 * and pinned to the lockfile integrity hashes. Tests and the license audit read
 * it; the page does not, so it adds nothing to the page bundle.
 */
export const REGISTRY_FACTS: FactsStore = generated as FactsStore;
