import type { SiteState, StudySetup, TeamMember } from "./types";

/** The vertical-slice study: a first-time biotech's randomized PK study. */
export const STUDY_24_081: StudySetup = {
  id: "24-081",
  title: "Study 24-081",
  design: "Randomized PK Study",
  sponsor: { name: "Arcadia Therapeutics", archetype: "firstTimeBiotech" },
  clinicalPhase: "I",
  subjects: 48,
  durationDays: 77,
  budget: 184_000,
  protocolMaturity: "questionable",
  regulatoryRisk: "moderate",
  complexity: 4,
};

export const STUDY_24_081_SITES: SiteState[] = [
  {
    id: "site-01",
    name: "Site 01",
    coordinator: "steady",
    burden: 40,
    enrolled: 0,
    openQueries: 0,
    deviations: 0,
    unsignedSource: 0,
    eligibilityConcerns: 0,
    trainingCurrent: true,
    lastAuditedDay: null,
  },
  {
    id: "site-02",
    name: "Site 02",
    coordinator: "terrified",
    burden: 55,
    enrolled: 0,
    openQueries: 0,
    deviations: 0,
    unsignedSource: 0,
    eligibilityConcerns: 0,
    trainingCurrent: true,
    lastAuditedDay: null,
  },
  {
    id: "site-03",
    name: "Site 03",
    coordinator: "invisible",
    burden: 65,
    enrolled: 0,
    openQueries: 0,
    deviations: 0,
    unsignedSource: 0,
    eligibilityConcerns: 0,
    trainingCurrent: false,
    lastAuditedDay: null,
  },
];

export const STUDY_24_081_TEAM: TeamMember[] = [
  {
    id: "maya",
    name: "Maya",
    role: "dataManager",
    archetype: "overloadedStar",
    skill: 5,
    speed: 3,
    reliability: 5,
    workload: 60,
  },
  {
    id: "priya",
    name: "Priya",
    role: "biostatistician",
    archetype: "optimisticStatistician",
    skill: 4,
    speed: 3,
    reliability: 3,
    workload: 40,
  },
  {
    id: "dana",
    name: "Dana",
    role: "regulatory",
    archetype: "steadyProfessional",
    skill: 4,
    speed: 4,
    reliability: 4,
    workload: 50,
  },
  {
    id: "walt",
    name: "Walt",
    role: "monitor",
    archetype: "veteranDataManager",
    skill: 5,
    speed: 3,
    reliability: 4,
    workload: 45,
  },
  {
    id: "lee",
    name: "Lee",
    role: "medicalWriter",
    archetype: "steadyProfessional",
    skill: 3,
    speed: 3,
    reliability: 4,
    workload: 20,
  },
  {
    id: "omar",
    name: "Omar",
    role: "programmer",
    archetype: "steadyProfessional",
    skill: 3,
    speed: 4,
    reliability: 3,
    workload: 30,
  },
];
