import type { NoticeSource } from "../types";

const COPYRIGHT_LINE = /^\s*(copyright\b|\(c\)|©)/i;

function splitCopyright(text: string): { copyrights: string[]; body: string } {
  const copyrights: string[] = [];
  const kept: string[] = [];
  for (const line of text.replace(/\r\n?/g, "\n").split("\n")) {
    if (COPYRIGHT_LINE.test(line)) copyrights.push(line.trim());
    else kept.push(line);
  }
  return { copyrights, body: kept.join("\n").trim() };
}

function fingerprint(body: string): string {
  return body.replace(/\s+/g, " ").toLowerCase();
}

/**
 * Render third-party notices. Packages sharing the same license body are listed
 * together above one copy of the text, each with its own copyright lines, so the
 * file keeps every required notice while staying small. Output is deterministic.
 */
export function renderThirdPartyNotices(sources: NoticeSource[]): string {
  const groups = new Map<
    string,
    { body: string; members: { label: string; copyrights: string[] }[] }
  >();
  const notices: string[] = [];

  const sorted = [...sources].sort(
    (a, b) => a.name.localeCompare(b.name) || a.version.localeCompare(b.version)
  );
  for (const src of sorted) {
    const { copyrights, body } = splitCopyright(src.licenseText);
    const key = fingerprint(body);
    const group = groups.get(key) ?? { body, members: [] };
    group.members.push({
      label: `${src.name}@${src.version} (${src.license})`,
      copyrights,
    });
    groups.set(key, group);
    if (src.noticeText?.trim()) {
      notices.push(
        `${src.name}@${src.version} NOTICE\n${src.noticeText.replace(/\r\n?/g, "\n").trim()}`
      );
    }
  }

  const header = [
    "THIRD-PARTY NOTICES",
    "",
    "This site is built on the open source packages listed below. Each package",
    "remains under its own license; the copyright notices and license texts that",
    "those licenses require are reproduced here. Generated by `npm run oss:credits`.",
    "",
    `${sorted.length} packages, ${groups.size} distinct license texts.`,
    "",
  ].join("\n");

  const orderedGroups = [...groups.values()].sort(
    (a, b) =>
      b.members.length - a.members.length || a.body.localeCompare(b.body)
  );
  const sections = orderedGroups.map((group, index) => {
    const lines = group.members.flatMap((m) => [
      `- ${m.label}`,
      ...m.copyrights.map((c) => `    ${c}`),
    ]);
    return [
      "=".repeat(78),
      `LICENSE TEXT ${index + 1} of ${orderedGroups.length}, applies to ${group.members.length} package(s):`,
      "",
      ...lines,
      "",
      group.body,
      "",
    ].join("\n");
  });

  const noticeSection = notices.length
    ? [
        "=".repeat(78),
        "NOTICE FILES (Apache-2.0 section 4(d))",
        "",
        notices.join("\n\n"),
        "",
      ].join("\n")
    : "";

  return [header, ...sections, noticeSection].filter(Boolean).join("\n") + "\n";
}
